# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Create a Github Release

on:
  push:
    branchs:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: MontyD/package-json-updated-action@master
        id: version-updated
        with:
          path: package.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        if: steps.version-updated.outputs.has-updated
        with:
          fetch-depth: 1
      - name: Create Release
        if: steps.version-updated.outputs.has-updated
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.version-updated.outputs.current-package-version }}
          release_name: v${{ steps.version-updated.outputs.current-package-version }}
          draft: false
          prerelease: false
